### ISSUE TITLE
为什么翻译时忽略指定的元素不能做成像只翻译指定的元素那样调用？

### ISSUE THREAD

**Issue by cqsn558** [xnx3/translate#30]
只翻译指定的元素的功能可以用同一种方法指定id 、class、tag，如document.getElementById('test1')我可以改为document.querySelector(‘#test1’)就可以只翻译指定id为test1的元素，虽然只能限定第一个id为test1，但可以通过编程用document.querySelectorALL(‘#test1’)实现限定所有id为test1的元素，但翻译时忽略指定的元素要通过不同的方法来限定id、class、tag，也就是translate.ignore.id.push、translate.ignore.class.push、translate.ignore.tag.push，这种就只能限定第一个，其他相同属性的就限定不了，我觉得应该用document.querySelectorALL(‘#test1’)这样的才可以限定所有相同属性元素。

**Comment by xnx3** [comment]
这个是限定多个的呢，比如 translate.ignore.class 它是个数组形态，可以有多个值， 你指的不行这块能方便提个验证不行的demo吗，我本地也运行试试看

**Comment by cqsn558** [comment]
我刚检查了一下我的代码，确实是我代码问题，是可以忽略指定相同class的多个元素，但如果想忽略某个元素下的子元素应该不行吧？比如以下html代码为：
<div class="zz"><font id="aa" class="aa">翻译时追加上自己想忽略不进行翻译的id的值</font><div><br>
<font id="aa" class="aa">翻译时追加上自己想忽略不进行翻译的id的值</font><br>
我只想忽略第一行的在<div>元素下class 为aa的元素就不知道怎么弄了，用translate.ignore.class.push('aa')会将两行都忽略，而只翻译指定的元素的功能我可以使用如下代码就可以只翻译第一行：
var setDocuments = [];
document.querySelectorAll('.zz>aa').forEach(function(element){
	setDocuments.push(element);
});
translate.setDocuments(setDocuments);

**Comment by xnx3** [comment]
这种只翻译某个元素中的第几个的确实是没有呢，当前只是固定的根据id、class、tag来进行设定，建议可以多用 class 的方式来进行设定，比如在不想翻译的元素上增加一个  class="ignore"
