### ISSUE TITLE
你们的这个开源项目太棒了，发现有一些init.json的访问请求失败，但并不知道是啥

### ISSUE THREAD

**Issue by lijingmt** [xnx3/translate#31]
我发现console里面，会有一些访问失败的翻译请求，再network里面可以查看，不知道是否影响效率，

**Comment by xnx3** [comment]
昨天出现了服务端不稳定的情况，现在用的人数比较多，服务端可能会出现不稳定的情况，不过只要用了最新v3版本的client.edge 模式，即使服务端出现了异常也不会影响正常使用的，切换到v3最新的 client.edge 模式可以参考：  http://translate.zvo.cn/43086.html   
另外也可以直接接入企业级高稳定翻译通道 http://translate.zvo.cn/43262.html    这两个就是应对v2版本 translate.service 使用太多不稳定的应对方案，可以看下。  client.edge 是全免费的，企业级稳定通道这个是收费的，可以优先选免费那个

**Comment by lijingmt** [comment]
非常感谢，发现翻译的还不精确，如果企业版可以达到chatgpt的水平，那就更好，支持你们，我们是网页游戏，所以你们这个js库特别好。

**Comment by xnx3** [comment]
谢谢，我们也在寻找可私有部署的大模型同时也具备很好的翻译能力，如果找到并对接上，这个翻译插件的实际使用性也肯定会更上一个台阶
