### ISSUE TITLE
[Feature]  浏览器插件支持

### ISSUE THREAD

**Issue by 0x5c0f** [xnx3/translate#34]
# 需求 

希望能创建一个google浏览器插件或者`Violentmonkey`的脚本，用于页面翻译来替代现有的的各类翻译插件 

# 功能要求

目前我在访问很多网站的时候都需要进行页面翻译，而当前的这个组建是我目前发现中翻译效果比较好的一个，但是目前似乎这个组建是作为个人站点嵌入的，我希望这个组建能增加一个浏览器插件，油猴或者`Violentmonkey`脚本都可以， 用来对任意网站进行翻译。

# 备注 
最后还有个问题，本来我是想自建节点来作为后端服务的，但是查看安装文档才发现，很多源码似乎已经并未公开了。而官网文档提供的安装脚本，也并不适合我现有的集成环境部署，如果可以，希望能在添加一个docker容器的集中部署方案。

**Comment by xnx3** [comment]
浏览器插件的，这里提供一个Chrome的插件，当然在像是edge了这种chrome内核的也能安装上，插件参考：  http://translate.zvo.cn/43220.html  

另外对于自建后端翻译服务节点的，这个已经不推荐了，一是需要懂后端知识、安装后很有可能会时不时维护这些都会给用户造成负担，而用户搞不定找到我们后会进而对我们产生精力消耗。 所以我们特意针对需要高稳定场景开放了企业翻译通道 ，可以参考  http://translate.zvo.cn/43262.html   我们来统一集中管理维护。  
而docker这个确实没考虑，我们本身计划的translate.service是跑在1核1G的极低配置服务器并且QPS能达到100， 所以我想让服务器做到最精简，能不安装的就不安装，让性能能更好的被translate.service所利用。

而随着2024年初v3版本的出现，开源免费版本我们更建议使用 client.edge 模式，可以参考：  http://translate.zvo.cn/43086.html   这个不在依赖后端服务  translate.service 了，所以 开源仓库里 translate.service 相关的也就全部移除了

**Comment by 0x5c0f** [comment]
感谢
