### ISSUE TITLE
如何分享时也保留当前的翻译效果

### ISSUE THREAD

**Issue by Mark-ait** [xnx3/translate#36]

**Comment by xnx3** [comment]
单纯 translate.js 它只是在浏览器上翻译，分享时，比如微信，它会自动通过分享的网址获取网页源代码，这时获取到的是翻译前的了。 分享后的也是被翻译的，可以结合这个来，直接对html文件进行翻译   http://translate.zvo.cn/41165.html  如果量级很大的话可以单独聊
