### ISSUE TITLE
最新版 3.5.1 translate.listener.start()  不生效了. 3.5.0 正常

### ISSUE THREAD

**Issue by HunterDestiny** [xnx3/translate#37]
动态插入的元素  translate.listener.start() 之后 3.5.0 可以. 3.5.1 不行

**Comment by xnx3** [comment]
3.5.1只是修复了几个小问题，应该不会吧，哥们你加一下QQ群 240567964 参考这个 http://translate.zvo.cn/43041.html 给我弄个简单的demo吧，我本地调试试试
