### ISSUE TITLE
广告过滤插件会影响翻译

### ISSUE THREAD

**Issue by vvangxp** [xnx3/translate#38]
这个JS太好用了，给作者点赞！

报告个小问题，貌似广告过滤插件会影响 JS 加载？
在 Microsoft Edge 浏览器 + uBlock Origin 扩展，网站无法翻译。错误如下：

The FetchEvent for "https://cdn.staticfile.net/translate.js/3.5.1/translate.js" resulted in a network error response: the promise was rejected.
Promise.then(异步)
(匿名) @ service-worker.js:140
service-worker.js:144 
        
Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:144:23

谷歌搜索了一下，说是广告过滤插件会影响。在 Google Chrome + AdBlock 下翻译正常。
在 Microsoft Edge 浏览器中关闭 uBlock 后正常。
客户用了哪款过滤插件我们没法干预，不知有没有解决方案？

**Comment by vvangxp** [comment]
更新一下，默认使用 <script src="https://cdn.staticfile.net/translate.js/3.5.1/translate.js"></script> 会被过滤掉，换到本地部署就没有问题了。

**Comment by xnx3** [comment]
> 更新一下，默认使用 <script src="https://cdn.staticfile.net/translate.js/3.5.1/translate.js"></script> 会被过滤掉，换到本地部署就没有问题了。

收到，之前还真没注意过这种情况

**Comment by xnx3** [comment]
> 更新一下，默认使用 <script src="https://cdn.staticfile.net/translate.js/3.5.1/translate.js"></script> 会被过滤掉，换到本地部署就没有问题了。

对了哥们，你下载最新的 3.5.3 版本， 3.5.1 有个小bug

**Comment by xnx3** [comment]
> 更新一下，默认使用 <script src="https://cdn.staticfile.net/translate.js/3.5.1/translate.js"></script> 会被过滤掉，换到本地部署就没有问题了。

https://github.com/xnx3/translate/blob/master/translate.js/translate.js

**Comment by vvangxp** [comment]
收到，已更新，会持续关注。
再次感谢。
