### ISSUE TITLE
inconsistency between capitals and lower case letters

### ISSUE THREAD

**Issue by cauzp** [xnx3/translate#39]
Many thanks to the developers for the excellent contribution. While I was using your project, I noticed a problem that when faced with phrase tasks, there is often a case inconsistency across the board. I hope that it is possible to improve the version so that so the translated content stays in lowercase, or the first letter is capitalized. At least it should be a uniform style. Thanks again to the author.

短文本翻译场景时，会出现大小写不统一的情况，希望作者可以改进为句首字母大写，或全部小写。

![image](https://github.com/user-attachments/assets/bd815285-c6d1-43ff-83d2-792a92dbf410)

**Comment by xnx3** [comment]
I'm very sorry, I saw it that day, but I forgot to reply after leaving for something else. Today, I released the latest version v3.8.0, which has been processed in all lowercase. However, there is an issue. In order not to affect the ability to customize terminology and offline translation settings, all lowercase processing has been placed on the server, which means that only those using the translate.service translation channel can achieve all lowercase processing, while those using the client-side translation channel have not been processed in all lowercase. Do you think this is helpful for you

**Comment by cauzp** [comment]
Thank you for your reply! I actually used an extra js control to accomplish this. It helps me to lowercase all the content and standardize the number of spaces at the end of the content, which makes the page neater.
