### ISSUE TITLE
是否支持或考虑支持忽略关键词的功能？

### ISSUE THREAD

**Issue by Lruihao** [xnx3/translate#43]
我有看到支持：

- 自定义翻译术语
- 忽略 ID
- 忽略 class
- 忽略 tag

似乎没有忽略关键词的功能。

例如：对于 `FixIt` 关键词，我希望所有的语言都不翻译，保持原状。

**Comment by xnx3** [comment]
忽略某个固定的字符串不进行翻译，这个目前没有呢，你可以考虑用  
`<span class="ignore">这里的文字不翻译</span>`
这种方式来指定它

**Comment by Lruihao** [comment]
> 忽略某个固定的字符串不进行翻译，这个目前没有呢。

好吧，因为我的文档是 markdown 渲染的，我不想修改原 markdown 的内容，然后基于这个库写了一个[插件](https://github.com/hugo-fixit/cmpt-translate)，所以还是比较希望支持一下这个功能。目前来说只好使用自定义术语替代一下了。

**Comment by xnx3** [comment]
非常抱歉，昨晚想着下班了，你提的问题没有非常详细的去看去思考，这方面我想一下哈

**Comment by gongchixin** [comment]
![WX20241206-140853](https://github.com/user-attachments/assets/2dcabfed-e387-46cd-8840-44fff8d8a96c)
![WX20241206-140906](https://github.com/user-attachments/assets/3db9e9f8-6bef-45ad-a1b1-88253450d802)
可以使用 自定义翻译，并修改js代码再渲染出 再处理一次。这样合理吗？

**Comment by xnx3** [comment]
> ![WX20241206-140853](https://private-user-images.githubusercontent.com/23138784/393117807-2dcabfed-e387-46cd-8840-44fff8d8a96c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjY3ODEsIm5iZiI6MTczMzQ2NjQ4MSwicGF0aCI6Ii8yMzEzODc4NC8zOTMxMTc4MDctMmRjYWJmZWQtZTM4Ny00NmNkLTg4NDAtNDRmZmY4ZDhhOTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2MjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NjE0YmZjNjFiMjMxYzU2MTk2MTQwOTA5ZmUxYWRlNmU5ZTY5NWU3YWU5NDVhOWNhYTYzMjE2MzBhZTUzMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fuC1q-zMvrxpWSM8FHT7umI2HapDA4FseG-4r523J2g) ![WX20241206-141407](https://private-user-images.githubusercontent.com/23138784/393118939-ab89fb48-7d4a-4757-85c0-f4b156fd6b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjY3ODEsIm5iZiI6MTczMzQ2NjQ4MSwicGF0aCI6Ii8yMzEzODc4NC8zOTMxMTg5MzktYWI4OWZiNDgtN2Q0YS00NzU3LTg1YzAtZjRiMTU2ZmQ2YjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2MjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTA4YzE2MTQ0MWJkZWU5ZDdjNDkwYmFmZTA3NzY2Nzk1ZjIxMmYwOGM0ODQ3MDBiMjQ2ODNiZDM2MmU0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k4GOXgDNr4xSscrInfuAEA_yWnZVw9dAXvJ4380PdZU) 可以使用 自定义翻译，并修改js代码再渲染出 再处理一次。这样合理吗？

这个自定义忽略翻译文本跟自定义术语的，我前几天就已经在做了，不出意外今天就能更新上来了，更新来后我把最新使用方法也在这里发一下

**Comment by xnx3** [comment]
@gongchixin @Lruihao  翻译时忽略指定的文本不被翻译，这个已增加，参考文档：  https://translate.zvo.cn/283381.html    js文件使用这个最新的  https://raw.githubusercontent.com/xnx3/translate/refs/heads/master/translate.js/translate.js    这个我本地初步简单测试没问题，可以加一下我微信  17076012262  如果遇到困难可以随时微信沟通，我看您的 [FixIt](https://github.com/hugo-fixit/FixIt) 项目很棒，我全力配合。  
还有咱这个项目有考虑过被赞助吗？ 我可以通过华为云那边对咱进行某些赞助，比如服务器

**Comment by Lruihao** [comment]
> @gongchixin @Lruihao  翻译时忽略指定的文本不被翻译，这个已增加，参考文档：  https://translate.zvo.cn/283381.html    js文件使用这个最新的  https://raw.githubusercontent.com/xnx3/translate/refs/heads/master/translate.js/translate.js    这个我本地初步简单测试没问题，可以加一下我微信  17076012262  如果遇到困难可以随时微信沟通，我看您的 [FixIt](https://github.com/hugo-fixit/FixIt) 项目很棒，我全力配合。  
> 
> 还有咱这个项目有考虑过被赞助吗？ 我可以通过华为云那边对咱进行某些赞助，比如服务器

感谢作者，我很快会在我的项目中跟进这个功能点。加您微信了。

**Comment by Lruihao** [comment]
我已在我的项目中集成忽略关键词的功能，目前来看一切正常。

**Comment by xnx3** [comment]
> 我已在我的项目中集成忽略关键词的功能，目前来看一切正常。

大赞
