### ISSUE TITLE
翻译api返回错误数据

### ISSUE THREAD

**Issue by xiyuesaves** [xnx3/translate#7]
![image](https://github.com/xnx3/translate/assets/25543545/6b0daa6e-fdbd-4e42-a3ec-f9fec4d91072)
![image](https://github.com/xnx3/translate/assets/25543545/2350ae6e-0beb-483f-af7e-c17abc4e06fd)
翻译api有很大概率返回请求内容，没有进行翻译，目前测试比较热门的语言会有这个问题，小语种翻译正常

**Comment by xnx3** [comment]
已修复这个问题，是缓存判断遇到了点问题直接把原文返回了，当前已修复
